spring.datasource.url=jdbc:postgresql://localhost:5432/interview_db
spring.datasource.username=postgres
spring.datasource.password=mahak@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

jwt.secret=mysupersecuresecretkeymysupersecuresecretkey123456789
jwt.expiration=86400000

#Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mahak.project.hr@gmail.com
spring.mail.password=ofxdkjzyeodwtbkc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Debugging
spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
app.name=InterviewHub
app.frontend.url=http://127.0.0.1:5501/Capstone_InterviewProcessTrackingSystem/frontend/src/pages

# File upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB