spring.datasource.url=jdbc:postgresql://localhost:5432/interview_db
spring.datasource.username=postgres
spring.datasource.password=mahak@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
